# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gre_words' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gre_words
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  use_frameworks!
  
  pod 'Socket.IO-Client-Swift', '~> 13.3.0'

end

